---
title: "Projects"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Projects}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(kwb.site)
```


# Tables

```{r echo = FALSE, warning=FALSE}
# Get project infos from KWB website
project_infos <- get_projects(debug = FALSE)
jsonlite::write_json(project_infos, "projects.json")
pi1 <- plot_gantt_chart_project(projects_json = "projects.json", 
                        tag_selection = "department", 
                        interactive = TRUE, 
                        interactive_export = TRUE)
pi2 <- plot_gantt_chart_project(projects_json = "projects.json", 
                        tag_selection = "topics", 
                        interactive = TRUE, 
                        interactive_export = TRUE)
pi3 <- plot_gantt_chart_project_by_funder(projects_json = "projects.json", 
                        interactive = TRUE, 
                        interactive_export = TRUE)
pi4 <- plot_gantt_chart_project(projects_json = "projects.json", 
                        tag_selection = "department", 
                        language_selection = "de",
                        interactive = TRUE, 
                        interactive_export = TRUE)
pi5 <- plot_gantt_chart_project(projects_json = "projects.json", 
                        tag_selection = "topics", 
                        language_selection = "de",
                        interactive = TRUE, 
                        interactive_export = TRUE)
pi6 <- plot_gantt_chart_project_by_funder(projects_json = "projects.json", 
                        language_selection = "de",                                          
                        interactive = TRUE, 
                        interactive_export = TRUE)
```

We have in total `r nrow(project_infos)` project websites in German and English 
on the KWB website.

## English

```{r}
project_infos_en <- project_infos %>%
  dplyr::filter(language == "en") 

jsonlite::write_json(project_infos_en , "projects_en.json")

DT::datatable(project_infos_en[,-3])

```

For `r nrow(project_infos_en)` projects the information is available in English.


## German

```{r}
project_infos_de <- project_infos %>%
  dplyr::filter(language == "de") 

jsonlite::write_json(project_infos_de, "projects_de.json")

DT::datatable(project_infos_de[,-3])

```

For `r nrow(project_infos_de)` projects the information is available in German.


# Plots


## English

### By Department

```{r fig.height=15, fig.width=9}
plot_gantt_chart_project(projects_json ="projects.json")

```

[Interactive plot: projects-by-department_en](../projects-by-department_en.html)


### By Topic

```{r fig.height=15, fig.width=9}
plot_gantt_chart_project(projects_json = "projects.json", tag_selection = "topic")
```

[Interactive plot: projects-by-topics_en](../projects-by-topics_en.html)

### By Funder

```{r eval = FALSE, fig.height=15, fig.width=9}
plot_gantt_chart_project_by_funder(projects_json = "projects.json")
```

[Interactive plot: projects-by-funder_en](../projects-by-funder_en.html)

## German

### By Department

```{r fig.height=15, fig.width=9}
plot_gantt_chart_project(projects_json ="projects.json",language_selection = "de")

```

[Interactive plot: projects-by-department_de](../projects-by-department_de.html)


### By Topic

```{r eval = FALSE, fig.height=15, fig.width=9}
plot_gantt_chart_project(projects_json ="projects.json",
                        tag_selection = "topic",
                        language_selection = "de")

```

[Interactive plot: projects-by-topics_de](../projects-by-topics_de.html)

### By Funder

```{r eval = FALSE, fig.height=15, fig.width=9}
plot_gantt_chart_project_by_funder(projects_json = "projects.json",
                                   language_selection = "de")
```

[Interactive plot: projects-by-funder_de](../projects-by-funder_de.html)
